doc on parameters
pallets-eco/flask-admin pull request #2338
Opened 2023-02-15 10:15 UTC by TheoLechemia

Small contribution on documentation.
See https://github.com/flask-admin/flask-admin/issues/1694
No sure if it's the way you want to do it.. tell me

2024-07-21 06:24 UTC, samuelhwilliams commented
Thanks for the suggested improvement to document env var configuration on Flask-Admin; I agree this is something we're missing at the moment.

We've just removed env var configuration for theming (swatch, fluid layout) and move it to a Theme config object passed to the admin instance. It looks like we still have two possible env vars: `ADMIN_RAISE_ON_INTEGRITY_ERROR` and `ADMIN_RAISE_ON_VIEW_EXCEPTION`. It would be good to add documentation for those. I think it makes sense to flag these at the bottom of 'introduction.rst' rather than hiding them in 'advanced.rst'.

If you wanted to update the PR I'd be very grateful - if not I'll try to get around to it soon.

2024-07-21 11:34 UTC, hasansezertasan requested changes

2024-07-21 11:34 UTC, hasansezertasan commented on doc/advanced.rst
> +  FLASK_ADMIN_SWATCH
Version 2 doesn't have this anymore.

2024-07-21 11:34 UTC, hasansezertasan commented on doc/advanced.rst
> +  FLASK_ADMIN_FLUID_LAYOUT
Version 2 doesn't have this anymore.

2024-07-22 23:17 UTC, hasansezertasan commented
> Thanks for the suggested improvement to document env var configuration on Flask-Admin; I agree this is something we're missing at the moment.
> 
> We've just removed env var configuration for theming (swatch, fluid layout) and move it to a Theme config object passed to the admin instance. It looks like we still have three possible env vars: `ADMIN_RAISE_ON_INTEGRITY_ERROR`, `ADMIN_RAISE_ON_VIEW_EXCEPTION` and `FLASK_ADMIN_SEARCH_SIZE_MAX`. It would be good to add documentation for those. I think it makes sense to flag these at the bottom of 'introduction.rst' rather than hiding them in 'advanced.rst'.
> 
> If you wanted to update the PR I'd be very grateful - if not I'll try to get around to it soon.

Looks like we have a lot more...

https://github.com/pallets-eco/flask-admin/blob/68bc6de4056c493a44b616e9bc4ac7850c0441fe/flask_admin/templates/bootstrap4/admin/lib.html#L259-L285

2024-07-23 06:39 UTC, samuelhwilliams commented
🥲  We should have a consistent namespace for all of these, too.

2024-07-23 07:11 UTC, TheoLechemia commented
Maybe I would take a look when the 2.0 will be almost stabilised ? 
I see there is still a `MAPBOX_MAP_ID` which is discuss here : https://github.com/pallets-eco/flask-admin/issues/2034

2024-07-23 08:04 UTC, samuelhwilliams commented
Thanks for flagging #2034 - agree that we should fix that interface. I've assigned myself to it and will think about what we want to do there.

For now I'm going to close this PR as I'll put one up shortly that rationalises all of the config variables under a FLASK_ADMIN_ namespace and adds some documentation.

2024-07-23 08:04 UTC, closed without merging