Update readme to add Pallets Ecosystem notice
pallets-eco/flask-admin pull request #2434
Opened 2024-06-25 20:21 UTC by samuelhwilliams

This commit converts the README from `.rst` to `.md`, and then adds the Pallets Community Ecosystem notice. I don't believe `.rst` files can show the same "Important" alert boxes and it feels correct to keep it visually consistent between projects.

2024-06-26 15:00 UTC, princerb commented
Is **flask-admin** not active anymore?

2024-06-27 10:23 UTC, Abdur-rahmaanJ commented
@princerb Just transferred to the Pallets!

2024-06-27 12:50 UTC, princerb commented
> @princerb Just transferred to the Pallets!

I see, but I also can see the date when the last commit was made. So this repo is inactive for this too long, and 78+ open pull requests. For this reason, I am afraid I am not willing to open my pull request while I have some contribution improvements for the project.

2024-06-27 13:22 UTC, aenglander commented
[`setup.py`](https://github.com/pallets-eco/flask-admin/blob/master/setup.py#L16) still references `README.rst` for the package's long description.

2024-06-27 13:47 UTC, samuelhwilliams commented
@aenglander good spot - have fixed that reference (and the reference in MANIFEST.in as well)

2024-06-27 14:47 UTC, aenglander requested changes

2024-06-27 14:47 UTC, aenglander commented on setup.py
> +    info = read("README.md")
[Setting long_description_content_type is required for Markdown](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata) as the [spec is to default to RST and fallback to plain text](https://packaging.python.org/en/latest/specifications/core-metadata/#description-content-type)

2024-06-30 22:21 UTC, aenglander approved these changes

2024-06-30 22:22 UTC, merged

2024-07-03 18:21 UTC, Abdur-rahmaanJ commented
@princerb We actually need more maintainers. Feel free to join the Pallets discord # pallets-eco channel ^^.